# Project information
site_name: Hello CTF
site_url: https://ctf.tj.cn/
site_author: 探姬
site_description: 开源免费、新手友好的CTF(Capture The Flag,夺旗赛)入门教程
# docs_dir: build
# Repository
repo_name: CTF-QuickStart
repo_url: https://github.com/ProbiusOfficial/CTF-QuickStart
edit_uri: https://github.com/ProbiusOfficial/CTF-QuickStart/tree/main/docs/

# Copyright
copyright: Copyright &copy; 2023 探姬

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    # - announce.dismiss        # 通知关闭
    - content.action.edit       # 编辑操作
    - content.action.view       # 查看操作
    - content.code.annotate     # 代码注释
    - content.code.copy         # 复制代码
    - content.tabs.link         # 标签链接
    - content.tooltips          # 工具提示
    # - header.autohide         # 自动隐藏头部
    # - navigation.expand       # 展开导航
    - navigation.indexes        # 导航索引
    - navigation.instant      # 即时导航
    # - navigation.prune        # 导航修剪
    # - navigation.sections     # 导航节
    # - navigation.tabs         # 导航标签
    # - navigation.tabs.sticky  # 固定导航标签
    - navigation.top            # 导航顶部
    - navigation.footer         # 导航底部
    - navigation.tracking       # 导航跟踪
    - search.highlight          # 搜索高亮
    - search.share              # 搜索分享
    - search.suggest            # 搜索建议
    - toc.follow                # 目录跟随
    # - toc.integrate           # 目录整合
  palette:
    - scheme: default
      primary: white
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

extra:
  disqus: 'open'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/probiusofficial
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/probiusofficial
    - icon: fontawesome/solid/video
      link: https://space.bilibili.com/27109929
  generator: false

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - 0. &nbsp; &nbsp; 前言:
    - ctf_preface/index.md
    - 0.1. &nbsp;  关于本书: ctf_preface/about.md
    - 0.2. &nbsp;  食用方法: ctf_preface/usage.md
    - 0.3. &nbsp;  加入我们: ctf_preface/join.md
    
  - 1. &nbsp; &nbsp; 快速开始:
    - ctf_start/index.md

  - 2. &nbsp; &nbsp; 环境设置:
    - ctf_evnset/index.md
    - 2.I. &nbsp; 工具一览: ctf_evnset/CTFtool.md
    - 2.II. &nbsp; Docker环境: ctf_evnset/Docker_On_Linux.md
    - 2.1. &nbsp; Web环境设置: ctf_evnset/Web.md
    - 2.2. &nbsp; MISC环境设置: ctf_evnset/MISC.md
    - 2.3. &nbsp; Crypto环境设置: ctf_evnset/Crypto.md

  - 3. &nbsp; &nbsp; MISC | 杂项:
    - ctf_misc/index.md
    - 3.1. &nbsp; 图片隐写: ctf_misc/stego.md
    - 3.2. &nbsp; 流量分析: ctf_misc/pcap.md
    - 3.3. &nbsp; 内存取证: ctf_misc/memory.md

  - 4. &nbsp; &nbsp; Web | 网络攻防:
    - ctf_web/index.md
    - 4.1. &nbsp; SQL注入: ctf_web/sql_injection.md
    - 4.2. &nbsp; XSS攻击: ctf_web/xss.md
    - 4.3. &nbsp; PHP反序列化: ctf_web/php_unserialize.md  
    
  - 5. &nbsp; &nbsp; Crypto | 密码学:
    - ctf_crypto/index.md
    - 5.1. &nbsp; 语义安全: ctf_crypto/Semantic_Security.md
    - 5.2. &nbsp; RSA: ctf_crypto/RSA.md
    - 5.3. &nbsp; ECC: ctf_crypto/ECC.md
    - 5.4. &nbsp; DES: ctf_crypto/DES.md
    - 5.5. &nbsp; AES: ctf_crypto/AES.md

  - 6. &nbsp; &nbsp; Reverse | 逆向工程:
    - ctf_reverse/index.md

  - 7. &nbsp; &nbsp; Pwn | 二进制安全:
    - ctf_pwn/index.md
    - 7.1. &nbsp; 栈上数组越界&栈溢出: ctf_pwn/Stack_Overflow.md

  - 8. &nbsp; &nbsp; 附录:
    - 8.1. &nbsp; 提问的智慧: ctf_appendix/how-to-ask.md
    - 8.2. &nbsp; CTF赛事: ctf_appendix/CTFevent.md
    - 8.3. &nbsp; NSSCTF平台使用: ctf_appendix/NSSCTF_Usage.md
    - 8.4. &nbsp; 推荐书单: ctf_appendix/book.md

  - x. &nbsp; &nbsp; 技能扩展:
    - x.1. &nbsp; 如何优雅的完成CTF命题: ctf_skill/makeChallenge.md



