# 项目信息 / Project information
site_name: Hello CTF
site_url: https://ctf.probius.xyz/
site_author: 探姬
site_description: 开源免费、新手友好的CTF(Capture The Flag,夺旗赛)入门教程

# 仓库信息 / Repository 
repo_name: Hello-CTF
repo_url: https://github.com/ProbiusOfficial/Hello-CTF
edit_uri: https://github.com/ProbiusOfficial/Hello-CTF/tree/main/docs/

# 版权声明 / Copyright
copyright: Copyright &copy; 2023 探姬

# 自定义配置部分 / Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    # - announce.dismiss        # 通知关闭
    - content.action.edit       # 编辑操作
    - content.action.view       # 查看操作
    - content.code.annotate     # 代码注释
    - content.code.copy         # 复制代码
    - content.tabs.link         # 标签链接
    - content.tooltips          # 工具提示
    # - header.autohide         # 自动隐藏头部
    # - navigation.expand       # 展开导航
    - navigation.indexes        # 导航索引
    - navigation.instant      # 即时导航
    # - navigation.prune        # 导航修剪
    # - navigation.sections     # 导航节
    - navigation.tabs         # 导航标签
    # - navigation.tabs.sticky  # 固定导航标签
    - navigation.top            # 导航顶部
    - navigation.footer         # 导航底部
    - navigation.tracking       # 导航跟踪
    - search.highlight          # 搜索高亮
    - search.share              # 搜索分享
    - search.suggest            # 搜索建议
    - toc.follow                # 目录跟随
    # - toc.integrate           # 目录整合

  # 调色板配置  
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # 字体配置        
  font:
    text: Noto Sans SC
    code: Fira Code

  favicon: assets/images/favicon.png

  logo: assets/images/logo.png
  
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

# 额外配置
extra:
  disqus: 'open' # 评论系统

  generator: false  

  # 页脚社交媒体
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/probiusofficial
    - icon: fontawesome/brands/github
      link: https://github.com/probiusofficial
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/27109929
    - icon: fontawesome/solid/paper-plane
      link: mailto:<probiuslinx@gmail.com> 

  # 谷歌分析
  analytics:
    provider: google
    property: G-V9998CDNR1

# Plugins
plugins:
  - search
  - blog

# 扩展
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
# # ----- mathjax -----
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# ----- katex -----
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

# ----- 页面统计 -----
  - javascripts/statis.js

# ----- other -----

extra_css:
# ----- katex -----
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

# ----- other -----
  - stylesheets/extra.css
  
# 目录
nav:

# 导航排布 —— | Hello CTF | 赛事 | 工具 | 团队 | 扩展 | Achieve | Blog

# - HelloCTF 内容 (.HC) Part ------------
  - HelloCTF: 
    - index.md
    - 前言:
      - HC_Preface/index.md
      - 关于本书: HC_Preface/about.md
      - 食用方法: HC_Preface/usage.md
      - 加入我们: HC_Preface/join.md

    - 快速开始:
      - HC_Start/index.md

    - 环境设置:
      - HC_envSet/index.md
      - 工具一览: HC_envSet/CTFtool.md
      - Docker环境: HC_envSet/Docker_On_Linux.md
      - Web环境设置: HC_envSet/Web.md
      - MISC环境设置: HC_envSet/MISC.md
      - Crypto环境设置: HC_envSet/Crypto.md

    - MISC | 杂项:
      - HC_MISC/index.md
      - 信息收集: HC_MISC/osint.md
      - 编码扩展: HC_MISC/Encode_extra.md
      - 文件基础: HC_MISC/file.md
      - 压缩包: HC_MISC/Archivefile.md
      - 隐写技术: HC_MISC/stego.md
      - 流量分析: HC_MISC/pcap.md
      - 内存取证: HC_MISC/memory.md
      - 附:文件签名表 : HC_MISC/file_sign.md

    - Web | 网络攻防:
      - HC_Web/index.md
      - Web入门题单: HC_Web/web_start.md
      - PHP基础: HC_Web/php_basic.md
      - PHP反序列化基础: HC_Web/php_unser_base.md 
      - SQL注入: HC_Web/sql_injection.md
      - XSS攻击: HC_Web/xss.md

    - Crypto | 密码学:
      - HC_Crypto/index.md
      - 1.前情提要: HC_Crypto/Recap.md
      - 2.编码基础: HC_Crypto/Encode.md
      - 3.古典密码: HC_Crypto/Classicalcipher.md

    - Reverse | 逆向工程:
      - HC_Reverse/index.md

    - Pwn | 二进制安全:
      - HC_PWN/index.md
      - 0. &nbsp; 汇编语言(x86): HC_PWN/Asm_x86.md
      - 1. &nbsp; 栈上数组越界&栈溢出: HC_PWN/Stack_Overflow.md
      - 1.1. &nbsp; ROP入门: HC_PWN/ROP.md
      - 1.2. &nbsp; 常见的ROP技巧: HC_PWN/ROP_Tricks.md
      - 2. &nbsp; 常见保护: HC_PWN/Protections.md
      - x. &nbsp; 杂七杂八的解题技巧: HC_PWN/Tricks.md

    - AWD:
      - 1. &nbsp; AWD介绍: HC_AWD/awd_about.md
      - 2. &nbsp; AWD平台: HC_AWD/awd_platform.md
      - 3. &nbsp; 【WEB】AWD技巧: HC_AWD/awd_web.exp.md
      - 4. &nbsp; 【PWN】AWD技巧: HC_AWD/awd_pwn.exp.md

    - 附录:
      - 提问的智慧: HC_Appendix/how-to-ask.md
      - CTF赛事: HC_Appendix/CTFevent.md
      - NSSCTF平台使用: HC_Appendix/NSSCTF_Usage.md
      - 推荐书单: HC_Appendix/book.md

# - CTF Event 赛事 (.TK) Part ------------
  - 赛事:
    - ET/index.md
    - 即将开始: ET/coming.md
    - 正在进行: ET/ongoing.md
    - 已经结束: ET/finished.md
    - 办赛指南:
      - ET/organize.md
    
# - CTF ToolKit 工具 (.TK) Part ------------
  - 工具: TK/index.md

# - TeamBuild (.TB) 团队 Part ------------
  - 团队: 
    - TB/index.md
    - 团队建设与运营:
      - TB/build.md
    - 团队纳新及培训:
      - TB/recruit.md
    - 团队训练及CTF平台:
      - TB/train.md


# - ExtensionEnhancement 扩展 (.EE) Part ------------
  - 扩展:
    - EE/index.md
    - Docker| 容器技术:
      - EE_Docker/index.md
      - 一文速通Docker(粗): EE_Docker/dockerstart.md
      - 关于Docker: EE_Docker/about.md 
      # - Windows下的Docker环境配置: EE_Docker/install_windows.md
      # - Linux下的Docker环境配置: EE_Docker/install_linux.md
      # - Docker的基本操作: EE_Docker/usage_basic.md
      # - Docker在CTF中的应用: EE_Docker/usage_ctf.md
      # - Web题目的Docker化: EE_Docker/usage_web.md
      # - 示例-经典web靶场封装: EE_Docker/usage_example.md
      # - Pwn题目的Docker化: EE_Docker/usage_pwn.md
      # - Crypto题目的Docker化: EE_Docker/usage_crypto.md
    - b. &nbsp; &nbsp; CTF命题:
      - EE_makeChallenge/index.md
      - b.1. &nbsp; 如何优雅的完成CTF命题: EE/makeChallenge.md

# - Archives 存档 (.AR) Part ----
  - Archives:
    - AR/index.md
    - 赛事归档:
      - AR/Events.md
    - 师傅们和他们的博客:
      - AR/friends.md
    - 联合战队信息/招新:
      - AR/Teams.md
    - 社区资源:
      - AR/Community.md
    - 书单推荐:
      - AR/books.md
    - 视频资源:
      - AR/Videos.md

# - Blog Part ----
  - Blog:
    - blog/index.md
 

