# 项目信息 / Project information
site_name: Hello CTF
site_url: https://hello-ctf.com/
site_author: 探姬
site_description: 开源免费、新手友好的CTF(Capture The Flag,夺旗赛)入门教程

# 仓库信息 / Repository 
repo_name: Hello-CTF
repo_url: https://github.com/ProbiusOfficial/Hello-CTF
edit_uri: https://github.com/ProbiusOfficial/Hello-CTF/tree/main/docs/

# 版权声明 / Copyright
copyright: Copyright &copy; 2024 探姬 

# 自定义配置部分 / Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    # - announce.dismiss        # 通知关闭
    - content.action.edit       # 编辑操作
    - content.action.view       # 查看操作
    - content.code.annotate     # 代码注释
    - content.code.copy         # 复制代码
    - content.tabs.link         # 标签链接
    - content.tooltips          # 工具提示
    # - header.autohide         # 自动隐藏头部
    # - navigation.expand       # 展开导航
    - navigation.indexes        # 导航索引
    - navigation.instant      # 即时导航
    # - navigation.prune        # 导航修剪
    # - navigation.sections     # 导航节
    - navigation.tabs         # 导航标签
    # - navigation.tabs.sticky  # 固定导航标签
    - navigation.top            # 导航顶部
    # - navigation.footer         # 导航底部
    - navigation.tracking       # 导航跟踪
    - search.highlight          # 搜索高亮
    - search.share              # 搜索分享
    - search.suggest            # 搜索建议
    - toc.follow                # 目录跟随
    # - toc.integrate           # 目录整合

  # 调色板配置  
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # 字体配置        
  font:
    text: Noto Sans SC
    code: Fira Code

  favicon: assets/images/favicon.png

  logo: assets/images/logo.png
  
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

# 额外配置
extra:
  disqus: 'open' # 评论系统

  generator: false  

  # 页脚社交媒体
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/probiusofficial
    - icon: fontawesome/brands/github
      link: https://github.com/probiusofficial
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/27109929
    - icon: fontawesome/solid/paper-plane
      link: mailto:<probiuslinx@gmail.com> 

  # 谷歌分析
  analytics:
    provider: google
    property: G-V9998CDNR1

# Plugins
plugins:
  - search
  - mkdocs-video: # Powered by https://github.com/soulless-viewer/mkdocs-video
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"

# 扩展
markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      #linenums: true # 显示行号
      #auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
# ----- SEO -----
  - javascripts/baidu_SEO.js
  
# # ----- mathjax -----
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# ----- katex -----
  - javascripts/katex.js 
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdn.bootcdn.net/ajax/libs/KaTeX/0.16.8/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

# ----- 页面统计 -----
  - javascripts/statis.js

# ----- other -----
  - javascripts/bannerSlider.js
  - javascripts/FullCalendar.js


extra_css:
# ----- katex -----
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.bootcdn.net/ajax/libs/KaTeX/0.16.8/katex.min.css

# ----- other -----
  - stylesheets/extra.css
  - stylesheets/bannerSlider.css
# 目录
nav:

# 导航排布 —— | Hello CTF | 赛事 | 工具 | 团队 | 扩展 | Achieve | Blog

# NEW 排布 —— | Home | 知识点标签 | 工具 | 靶场 | 赛事 | 归档

# - Home 主要内容 (.HC) Part ------------
  - Home:
    - home/index.md
    - 快速开始:
      - hc-start/index.md

    - 前言:
      - hc-preface/index.md
      - 关于本书: hc-preface/about.md
      - 食用方法: hc-preface/usage.md
      - 加入我们: hc-preface/join.md

    - 环境设置:
      - hc-env/index.md
      - 工具一览: hc-env/CTFtool.md
      - Docker环境: hc-env/Docker_On_Linux.md
      - Web环境设置: hc-env/Web.md
      - MISC环境设置: hc-env/MISC.md
      - Crypto环境设置: hc-env/Crypto.md

    - MISC | 杂项:
      - hc-misc/index.md
      - 信息收集: hc-misc/osint.md
      - 编码扩展: hc-misc/Encode_extra.md
      - 文件基础: hc-misc/file.md
      - 压缩包: hc-misc/Archivefile.md
      - 隐写技术: hc-misc/stego.md
      - 流量分析: hc-misc/pcap.md
      - 内存取证: hc-misc/memory.md
      - 附:文件签名表 : hc-misc/file_sign.md

    - Web | 网络攻防:
      - hc-web/index.md
      - Web入门题单: hc-web/web_start.md
      - PHP基础: hc-web/php_basic.md
      - PHP反序列化基础: hc-web/php_unser_base.md 
      - SQL注入: hc-web/sql_injection.md
      - XSS攻击: hc-web/xss.md
      - 文件包含: hc-web/include.md
      - SSTI注入: hc-web/ssti.md

    - Crypto | 密码学:
      - hc-crypto/index.md
      - 前情提要: hc-crypto/Recap.md
      - 编码基础: hc-crypto/Encode.md
      - 古典密码: hc-crypto/Classicalcipher.md

    - Reverse | 逆向工程:
      - hc-reverse/index.md
      - 引导篇：灵魂F&Q: hc-reverse/引导篇：灵魂F&Q.md
      - Quick Start：可执行文件: hc-reverse/Quick Start：可执行文件.md
      - Quick Start：ASM汇编: hc-reverse/Quick Start：ASM汇编.md
      - Quick Start：Example problems: hc-reverse/Quick Start：Example problems.md
      - 从零开始的IDA: hc-reverse/从零开始的IDA.md
      - 从零开始的壳: hc-reverse/从零开始的壳.md

    - Pwn | 二进制安全:
      - hc-pwn/index.md
      - 汇编语言(x86): hc-pwn/Asm_x86.md
      - 栈上数组越界&栈溢出: hc-pwn/Stack_Overflow.md
      - ROP入门: hc-pwn/ROP.md
      - 常见的ROP技巧: hc-pwn/ROP_Tricks.md
      - 常见保护: hc-pwn/Protections.md
      - 杂七杂八的解题技巧: hc-pwn/Tricks.md

    - AWD | 攻防模式:
      - AWD介绍: hc-awd/awd_about.md
      - AWD平台: hc-awd/awd_platform.md
      - 【WEB】AWD技巧: hc-awd/awd_web.exp.md
      - 【PWN】AWD技巧: hc-awd/awd_pwn.exp.md

    - AI | 人工智能安全:
      - hc-ai/index.md
      - 初识AI: hc-ai/What_is_AI.md
      - 你的第一个神经网络: hc-ai/MLP.md

    - blockchain | 区块链安全:
      - Move:
        - 从0开始的签到题: hc-blockchain/Move/0x00.md

    - 附录:
      - 提问的智慧: hc-appendix/how-to-ask.md
      - CTF赛事: hc-appendix/CTFevent.md
      - NSSCTF平台使用: hc-appendix/NSSCTF_Usage.md
      - 推荐书单: hc-appendix/book.md

  - 知识点标签:
    - hc-tags/index.md
    - Web: 
      - hc-tags/web/index.md
      - PHP特性: hc-tags/web/PHP_features.md

# ----- 暂时下线 time: 2024-01-07 -----
# # - CTF Training 练习 (.Training) Part ------------
#   - 刷题:
#     - Training/index.md

# - CTF Event 赛事 (.Event) Part ------------
  - 赛事:
    - Event/index.md
    - 即将开始: Event/Upcoming_events.md
    - 正在进行: Event/Now_running.md
    - 已经结束: Event/Past_events.md
    - 办赛指南:
      - Event/organize.md

# - Hello CTF 系列靶场文档
  - 靶场: hc-labs/index.md

# - CTF toolkit 工具 (.toolkit) Part ------------
  - 工具: toolkit/index.md

# - CTF 归档部分
  - 归档: hc-archive/index.md

# ----- 合并到主页中 time: 2024-01-07 ----- 
# - TeamBuild (.TeamBuild) 团队 Part ------------
  # - 团队: 
  #   - TeamBuild/index.md
  #   - 团队建设与运营:
  #     - TeamBuild/build.md
  #   - 团队纳新及培训:
  #     - TeamBuild/recruit.md
  #   - 团队训练及CTF平台:
  #     - TeamBuild/train.md

# ----- 合并到主页中 time: 2024-01-07 ----- 
# - Set Challenges (.SC) 命题 Part ------------
  # - 命题: 
  #   - Create/index.md
  #   - 一般题目模板 : docker-template/index.md
  #   - 动态容器原理: Create/DynamicChallengePrinciples.md
  #   - Web基础靶机构建流程: Create/WebBaseChallenge.md


#  ----- 合并到主页中 time: 2024-01-07 ----- 
# - ExtensionEnhancement 扩展 (.EE) Part ------------
  # - 扩展:
  #   - EE/index.md
  #   - Docker| 容器技术:
  #     - EE_Docker/index.md
  #     - 一文速通Docker(粗): EE_Docker/dockerstart.md
  #     - 关于Docker: EE_Docker/about.md 
      # - Windows下的Docker环境配置: EE_Docker/install_windows.md
      # - Linux下的Docker环境配置: EE_Docker/install_linux.md
      # - Docker的基本操作: EE_Docker/usage_basic.md
      # - Docker在CTF中的应用: EE_Docker/usage_ctf.md
      # - Web题目的Docker化: EE_Docker/usage_web.md
      # - 示例-经典web靶场封装: EE_Docker/usage_example.md
      # - Pwn题目的Docker化: EE_Docker/usage_pwn.md
      # - Crypto题目的Docker化: EE_Docker/usage_crypto.md

#  ----- 合并到主页中 time: 2024-01-07 ----- 
# - Archives 存档 (.Archive) Part ----
  # - Archives:
  #   - hc-archive/index.md
  #   - 赛事归档:
  #     - hc-archiveEvents.md
  #   - 师傅们和他们的博客:
  #     - hc-archive/friends.md
  #   - 联合战队信息/招新:
  #     - hc-archiveTeams.md
  #   - 社区资源:
  #     - hc-archiveCommunity.md
  #   - 书单推荐:
  #     - hc-archivebooks.md
  #   - 视频资源:
  #     - hc-archiveVideos.md

# ----- 停用 -----
# - Blog Part ----
  # - Blog:
  #   - blog/index.md

watch:
  - docs
  - mkdocs.yml
  - overrides/partials